### ISSUE TITLE
How many time did you spend on testing?

### ISSUE THREAD

**Issue by Okityou** [vislearn/LessMore#11]
Hello, I used your pretrained model to test on the dataset on a gpu(Tesla K80) , but cost a long period without a result. Can you give me the actual testing time of the model?
![image](https://user-images.githubusercontent.com/44048634/57852084-cb7a9c00-7814-11e9-8090-43e89466ae7d.png)

**Comment by ebrach** [comment]
Hi, 
the method seems to be unable to find valid hypotheses, which indicates that the scene coordinate prediction failed. 

Most likely there is something wrong with the LUA/CUDA/C++ communication on your machine. I suspect the LUA methods do not run through (unfortunately there is no proper error handling in the code which means that LUA errors will just be swallowed by C++). To debug this, you could add console outputs (e.g. print('done')) to the end of each LUA method in train_obj.lua and train_score.lua.

Btw. I assume you are using the original DSAC code? However, this is the DSAC++ repository. 

Kind regards.
Eric
