### ISSUE TITLE
Camera calibration matrix of Cambridge landmark

### ISSUE THREAD

**Issue by wanyiming2017** [vislearn/LessMore#12]
Could you tell me the camera intrinsic of Cambridge landmark? It seems the camera intrinsic you provided in your code belongs to 7 Scenes.

**Comment by ebrach** [comment]
Hi, the data package linked in the Github readme contains configuration files for each dataset. You find all calibration parameters there.

Kind regards,
Eric

**Comment by sherwoac** [comment]
Save yourself the 6.1GB download, this is the contents of cambridge/default.config:
#dataset parameters 

fl      744.375
xs      0.0
ys      0.0

iw      852
ih      480

#testing parameters

rI      256
rRI     100

rT      10

rdraw   1
