### ISSUE TITLE
Mapping Depth to RGB & Pose Correction

### ISSUE THREAD

**Issue by fiducialz** [vislearn/LessMore#13]
In DSAC codebase for the 7Scenes dataset, there is a function that maps depth to RGB (mapDepthToRGB) that is not done here. Why do you not need to map depth to RGB here? Also, in DSAC there is a correction applied to the pose that is no longer done here. Why do you not need the correction any more?

**Comment by ebrach** [comment]
We assume mapped (=registered) depth here, which is really the standard case. 7Scenes having unregistered depth maps is an artifact (or flaw) of this particular dataset. The mapping process itself would also vary between datasets, hence it should be part of the dataset pre-processing. You could modify the DSAC code to register and store the original 7Scenes depth maps, or you use the rendered and registered depth maps that we provide (links in the readme).

The pose correction you mention was a matter of transforming between camera pose conventions. This code works with the pose convention used in the 7Scenes dataset, so a correction is not necessary anymore. I'm not sure, whether this correction was actually necessary for DSAC - it might have been a remnant of previous projects.

**Comment by neuralinspire** [comment]
Can you tell us exactly how you generated the training depth files for 7Scenes? They don't look like what you would get after applying the transforms in DSAC.

Thanks!

**Comment by ebrach** [comment]
They are renderings of the 7Scenes 3D models using ground truth poses and the RGB camera calibration parameters, i.e. they are NOT transformed versions of the Kinect depth measurements.
