### ISSUE TITLE
Scene Pose vs Camera Pose

### ISSUE THREAD

**Issue by fiducialz** [vislearn/LessMore#14]
Is there a reason for estimating the scene pose vs the camera pose?

**Comment by ebrach** [comment]
Parts of the algorithm, mostly implemented using OpenCV, like 3D point projection or the PnP solver, require or estimate the scene pose (inverse of the camera pose). Therefore, it is more convenient to consistently work with the scene pose, and to invert it in the very end to get the camera pose.
