### ISSUE TITLE
Training Time issue

### ISSUE THREAD

**Issue by HelloEI** [vislearn/LessMore#15]
Hi, Thanks for your work! I am reproducing the work follow your introduction. At RANSAC training step, it costed almost five days to finish the training. I just want to know how long did you finish the training parts of Chess dataset without depth information and which GPU are you used for it?
Is the code support multi-GPU training?
Thanks a lot!

**Comment by ebrach** [comment]
Hi,
We let it train for 2 days on a Tesla K80 GPU in which it did about 50k iterations / network parameter updates.

You might also want to verify that you get a reasonable loss during end-to-end training, i.e. for 7scenes generally below 5cm translation error from the start. If the initialization stages failed, or if end-to-end training diverges, RANSAC might take a long time to find valid hypotheses during end-to-end training.
