### ISSUE TITLE
projectPoints vs project

### ISSUE THREAD

**Issue by Okityou** [vislearn/LessMore#16]
Hi, Thanks for your work! When I was looking at your code, I found that you used the project function you wrote in the second step to optimize the reprojection error, but the "projectPoints" function provided by opencv was indeed used in the third step to optimize the reprojection error. I don't know the difference between the two functions, do the two functions get the same projection point? At the same time, I am a little confused about the preprocessing of the image. Will rescaling and cropping not affect the pose?

**Comment by ebrach** [comment]
Hi,
regarding the project function: The OpenCV function takes a set of 3D points, and calculates their 2D projections. The custom project function calculates the 1D reprojection error of a single point. You are right, that they  are very related. I do not remember the exact details anymore, but I assume it was convenient in some places of the code to have a function that takes a single point as input.

regarding scaling and cropping: These operations affect the internal calibration parameters of the camera. Scaling changes the focal length, and cropping moves the principal point. We adjust these parameters accordingly.

Best,
Eric

**Comment by Okityou** [comment]
Thank you for you reply.

**Comment by Okityou** [comment]
Thank you for your reply.
