### ISSUE TITLE
Calculate target scene coordinates using 3D model

### ISSUE THREAD

**Issue by dihuangdh** [vislearn/LessMore#17]
Hi, @ebrach 

Thanks for your awesome work!

In the paper, DASC++ shows good results using 3D model. But seems in this project you only use depth to render scene coordinates. I tried it on 7scenes, but find 3D model can't align with the images.

Did you meet the same problem? And will you release the related code ? 

Best.

**Comment by jaswant7** [comment]
@dihuangdh 
Hello 
Were you able to align 3D model with the images ?

Thanks
