### ISSUE TITLE
Pose Input

### ISSUE THREAD

**Issue by maesfahani** [vislearn/LessMore#2]
Hi,
How can I create the position input for Cambridge dataset?
The format is different to 7 scene

**Comment by ebrach** [comment]
Yes, input poses have to be 4x4 transformation matrices for our code. The Cambridge dataset format (translation vectors + quaternions) can be easily converted using a math library of your choice.

**Comment by shamafiras** [comment]
Hey,
On the same topic, I wanted to reproduce your reported performance number on Cambridge dataset, based on the pre-trained networks you provide. 
To convert from Cambridge format to 4x4 transformation matrices, I used transforms3d.quaternions.quat2mat (from transforms3d package in python) which then I feed to the test code. 
However, during test-time (and evaluation ) I get huge rotation errors for each pose (while translation error is okey)
for example: 
for the input image seq1/frame00001.png in ShopFacade scene, 
which have the following quaternions: [0.712261, 0.682691, -0.123193, 0.106962], 
and translation: -0.157816 -10.413150 1.832074
I get the following matrix (after applying quat2mat() ):
9.4676524e-01      -3.2057519e-01     -2.9447146e-02      -1.5781600e-01
-1.5835781e-02     4.4984371e-02      -9.9886217e-01      -1.0413150e+01
3.2153509e-01,      9.4615430e-01       3.7513080e-02        1.8320740e+00
0.0000000e+00      0.0000000e+00      0.0000000e+00        1.0000000e+00

The predicted pose output ({Rodriguez},{translation}) of this image is : [{-1.51317 0.26542 -0.232277 }, {-0.0721703 -10.4599 1.81715} ] 

when the result is compared to this gt pose in DSAC++ code I get the following rotError: 178.183[deg]

I wonder how exactly you covert from quaternions to 4x4 matrix, can you please help.

Thanks

**Comment by ebrach** [comment]
This is how I convert the Cambridge poses. It could be that you have to invert the 4x4 matrix on top of that. This has to be done for either the Cambridge or the 7scenes poses to work with the DSAC++ code, but I do not recall which one atm.


	import numpy as np
	import cv2 as cv
	
	# this is the 4-value quaternion from the Cambridge file
	cam_rot = [float(r) for r in camera[4:]]

	#quaternion to axis-angle
	angle = 2 * math.acos(cam_rot[0])
	x = cam_rot[1] / math.sqrt(1 - cam_rot[0]**2)
	y = cam_rot[2] / math.sqrt(1 - cam_rot[0]**2)
	z = cam_rot[3] / math.sqrt(1 - cam_rot[0]**2)

	cam_rot = [x * angle, y * angle, z * angle]
	
	cam_rot = np.asarray(cam_rot)
	cam_rot, _ = cv.Rodrigues(cam_rot)

	# this is the 3-value translation vector from the Cambridge file
	cam_trans = [float(r) for r in camera[1:4]]
	cam_trans = np.asarray([cam_trans])
	cam_trans = np.transpose(cam_trans)
	cam_trans = - np.matmul(cam_rot, cam_trans)

	cam_pose = np.concatenate((cam_rot, cam_trans), axis = 1)
	cam_pose = np.concatenate((cam_pose, [[0, 0, 0, 1]]), axis = 0)

**Comment by shamafiras** [comment]
Thanks a lot, that makes sense now, I wonder however why you perform the following line:
cam_trans = - np.matmul(cam_rot, cam_trans)
it seems like you calculate the Translation of the inverse transform but use the camera rotation as is (i.e. without inverse it). can you please explain that
