### ISSUE TITLE
Why i can't get the Graduated Colors by using convertForDisplay function in util.cpp?

### ISSUE THREAD

**Issue by hm510** [vislearn/LessMore#21]
hi, Thanks for your work! 
Here is my issue: when i used convertForDisplay function in util.cpp to convert a coordinate map into a rgb image, i can't get the  Graduated Colors like your paper done. Is there any postprocessing i haven't use or i  use the wrong value of parameter maxExtent in convertForDisplay function？ What's the excat meaning of this parameter?

Your code in project LessMore 
`cv::Mat convertForDisplay(const jp::img_coord_t& img, float maxExtent);`
Thanks

**Comment by hm510** [comment]
ok, now i can get a more smooth coordinate map by change the type of coord from int to double in util.cpp, but i still want to know what is the excat meaning of maxExtent?
Thanks for your reply!

**Comment by ebrach** [comment]
Hi,
we visualize scene coordinates by mapping XYZ to the RGB cube. For this mapping, we need to know the maximum value a scene coordinate can take, such that we can map it correctly to the color range 0-255. As such, maxExtent should be the maximum extent of your scene in either X, Y, or Z direction. Note that we assume that the scene coordinate frame is zero centered. You can get the maxExtent for a specific scene by iterating over your ground truth scene coordinate, keeping track of the maximum values of scene coordinates.

Hope that helps,
Eric

**Comment by hm510** [comment]
ok, i got it!
Thanks for your reply!
