### ISSUE TITLE
questions about utilizing a scene coordiante heuristic based on a constant depth assumption 

### ISSUE THREAD

**Issue by Guan2014** [vislearn/LessMore#23]
Hi eric,
I am confused about utilizing a scene coordiante heuristic based on a constant depth assumption. I think the constant depth assumption will  force the predicted coordinates to be in front of the camera. However, it looks like the predicted coordinates can be located on the ray that starts with the camera center and passes through the corresponding pixel, which still meet the low reprojection error. So maybe the predicted coordinates are not in the same scale as the ground truth. Can you expalin it for me?

**Comment by ebrach** [comment]
It is correct, that by optimizing the reprojection error (training step two) we only constrain the scene coordinate to lie anywhere on the corresponding pixel ray. However, throughout training, the network sees the same scene coordinate from many different view points (i.e. different pixel rays) which seems to suffice to constraint the scene coordinate to the correct depth. That means, the network performs an implicit triangulation of scene coordinate throughout training.

I hope that clears things up a bit!
Eric

**Comment by Guan2014** [comment]
Thanks for your explanation. What I understand is that if the pixel p1 in a frame I1 is corresponding to pixel p2 in frame I2, then their feature embedding will be similar and their predicted coordinates will be nearly the same.  Minimizing the reprojection error will force their corresponding coordinate to be the correct position. Is it right?

**Comment by ebrach** [comment]
Yes, this is a good summary. Another way to put it in words: Since the network has limited model capacity, it has to learn a smooth and geometrically consistent representation of the scene. This is only possible, if scene coordinates have a consistent (ie correct) depth.

**Comment by Guan2014** [comment]
I got it. Thanks for your reply.
