### ISSUE TITLE
The intrinsic paramters of Cambridge dataset

### ISSUE THREAD

**Issue by Poiw** [vislearn/LessMore#25]
Hi @ebrach,
I want to generate 3D coordinates from depth images. However, I didn't find the camara intrinsic parameters in Cambridge dataset after checking the package linked in readme. Could you tell me the intrinsic paramters of Cambridge dataset or where I can find it.

regards.

**Comment by ebrach** [comment]
Hi,

in the readme there is a data package linked. It contains a folder for the Cambridge dataset with a default.config file. This file states the intrinsics that we use. Focal length: 744.375 (for images rescaled to 480px height) and principal point assumed in the image center.

Kind regards,
Eric
