### ISSUE TITLE
Using sparse depth maps

### ISSUE THREAD

**Issue by mtee** [vislearn/LessMore#3]
Hi, I am interested in using your algorithm with depth maps provided by a stereo camera. These depth maps are very sparse in the environments with a low number of features, so sometimes just about 10-20% of pixels in the RGB image have a valid depth value (others are 0). I was thinking about replacing the zeros with the dP.constD value. However seeing, that you are not doing this in your code made me think that I might have missed something. Do you think it's better to throw away the sparse depth map and just use the const depth? Or rather fill the depth maps with the const depth value, where there is no real depth data? Or just leave it as it is, i.e.:
```
if(depthData(y, x) == 0)
   {
        img(y, x) = jp::coord3_t(0, 0, 0);
        continue;
  }
```

**Comment by ebrach** [comment]
Hey,

the constD trick is a very crude tool that's only justified if you have no information about the correct depth. In your case, there is quite a lot of information available (even if it is sparse). I would try to create dense maps from your sparse maps using interpolation / hole filling methods, and train with those dense maps. Even if they are not perfect, training stage two (optimizing reprojection error) will probably fix errors in many places.  

As a first quick and dirty check, you could just do nearest neighbor interpolation of your sparse depth (assign the depth of the nearest pixel with a value). Maybe do early stopping in training stage one to avoid overfitting to these interpolated depth maps.

Kind regards,
Eric
