### ISSUE TITLE
Compilation issues: Error in make

### ISSUE THREAD

**Issue by anonymous2792** [vislearn/LessMore#4]
Hi,
Can you help me with some errors in compilation. I don't have experience with Lua or torch, so was not able to figure out the error. The screen shot is attached. 
![screenshot from 2018-08-08 10-09-07](https://user-images.githubusercontent.com/37577615/43812482-1b62a81a-9af4-11e8-97a0-08b24036d846.png)

**Comment by ebrach** [comment]
Hi, 
please make sure you have liblua and the associated liblua-dev package installed.

Kind regards,
Eric

**Comment by muma1018** [comment]
First of all, thanks for providing your code!

I run into the same Error. I have lua5.3 and lua5.3-dev package installed. I'm on Ubuntu 16.04.
Do you have further hints on that?

Best, Markus

**Comment by ebrach** [comment]
The error suggests that your linker cannot find the LUA library. I think this issue is not connected to our code specifically. Do the LUA bindings work in a separate, minimal code example?

**Comment by muma1018** [comment]
I checked the links again and even though my current LUA version is 5.3 I switched back to 5.1 and adapted it in the _CMakeLists.txt_ file at line 14 _include_directories(/usr/include/lua5.1)_

Thanks for your response Eric.

**Comment by ebrach** [comment]
And did this solve your problem?

**Comment by muma1018** [comment]
Yes, the compilation was successful.

**Comment by ebrach** [comment]
Thanks, great!

**Comment by jujumo** [comment]
I ran into the same problem, and solve the compilation adding lua to:
>  target_link_libraries(train_obj ${PNG_LIBRARY} ${OpenCV_LIBS} luajit lua)

But then I have a `segmentation fault` at runtime. Can you provide more insights about the lua / torch / luajit versions you have installed ?

Best, Julien

**Comment by ebrach** [comment]
Hi Julien,
atm I have no running Torch installation but I can reconstruct the following from my old files:
Torch source commit 20e523771377568841e9d11bc3275a4404edcd1e (Oct 18 2017)
LUA 5.1.5
LuaJIT 2.1.0-beta1

Are you sure your segmentation fault is connected to Torch/LUA? Maybe it's an issue with your data setup. At which point exactly does the segmentation fault occur?

Kind regards,
Eric
