### ISSUE TITLE
the trained model is general?

### ISSUE THREAD

**Issue by yvaine** [vislearn/LessMore#5]
Hi, Good Job!
I have some confusions.If I have trained in one dataset, can i use it in another different unseen data? Is the model general to different environment?

**Comment by ebrach** [comment]
Hi Yvaine,
our pipeline learns to regress absolute poses relative to a specific scene coordinate system. In an unseen environment, absolute pose regression cannot work, because the coordinate frame is unknown.

**Comment by yvaine** [comment]
Thank you for your replay @ebrach . Is this pipeline wait for longer time than visual slam, because this learning process is not online, visual slam can do that mapping process online. Is there some learning method should fit to general environment, so faster than visual slam.

**Comment by ebrach** [comment]
This work might be of interest to you: https://arxiv.org/abs/1702.02779
